-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 08:08:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_sgc
-- -----------------------------------------------------
-- Base de datos del Sistema de Getión de Calidad del Patrotano Universitario

-- -----------------------------------------------------
-- Schema bd_sgc
--
-- Base de datos del Sistema de Getión de Calidad del Patrotano Universitario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sgc` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `bd_sgc` ;

-- -----------------------------------------------------
-- Table `bd_sgc`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Puesto` (
  `id_puesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(100) NULL,
  `ruta` VARCHAR(50) NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Usuario` (
  `num_empleado` INT NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `id_puesto` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  `estatus` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`num_empleado`, `id_departamento`),
  INDEX `fk_usuarios_puesto_idx` (`id_puesto` ASC),
  INDEX `fk_usuarios_rol1_idx` (`id_rol` ASC),
  UNIQUE INDEX `num_empleado_UNIQUE` (`num_empleado` ASC),
  INDEX `fk_Usuario_Departamento1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_usuarios_puesto`
    FOREIGN KEY (`id_puesto`)
    REFERENCES `bd_sgc`.`Puesto` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `bd_sgc`.`Rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `bd_sgc`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Clasificador_Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Clasificador_Actividad` (
  `id_clasificador_actividad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `color` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_clasificador_actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Actividad` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_clasificador_actividad` INT NOT NULL,
  `lugar` VARCHAR(50) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estatus` INT NOT NULL,
  PRIMARY KEY (`id_actividad`),
  INDEX `fk_actividades_clasificador_actividades1_idx` (`id_clasificador_actividad` ASC),
  CONSTRAINT `fk_actividades_clasificador_actividades1`
    FOREIGN KEY (`id_clasificador_actividad`)
    REFERENCES `bd_sgc`.`Clasificador_Actividad` (`id_clasificador_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Tipo_Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Tipo_Documento` (
  `id_tipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Tipo_Archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Tipo_Archivo` (
  `id_tipo_archivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `ruta` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_archivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Clasificador_Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Clasificador_Documento` (
  `id_clasificador_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_clasificador_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Documento` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `ruta` VARCHAR(100) NOT NULL,
  `id_tipo_archivo` INT NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estatus` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `id_clasificador_documento` INT NOT NULL,
  `orden_documento` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_documento`),
  UNIQUE INDEX `id_documentos_UNIQUE` (`id_documento` ASC),
  INDEX `fk_documentos_tipo_documento1_idx` (`id_tipo_documento` ASC),
  INDEX `fk_documentos_tipo_archivo1_idx` (`id_tipo_archivo` ASC),
  INDEX `fk_documentos_clasificador_documentos1_idx` (`id_clasificador_documento` ASC),
  INDEX `fk_documentos_departamentos1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_documentos_tipo_documento1`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `bd_sgc`.`Tipo_Documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_tipo_archivo1`
    FOREIGN KEY (`id_tipo_archivo`)
    REFERENCES `bd_sgc`.`Tipo_Archivo` (`id_tipo_archivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_clasificador_documentos1`
    FOREIGN KEY (`id_clasificador_documento`)
    REFERENCES `bd_sgc`.`Clasificador_Documento` (`id_clasificador_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `bd_sgc`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Formulario_Reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Formulario_Reunion` (
  `id_reunion` INT NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(100) NOT NULL,
  `fecha_reunion` DATETIME NOT NULL,
  `objetivo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_reunion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Acuerdo_Reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Acuerdo_Reunion` (
  `id_acuerdo` INT NOT NULL AUTO_INCREMENT,
  `id_reunion` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `id_usuario_responsable` INT NOT NULL,
  PRIMARY KEY (`id_acuerdo`),
  INDEX `fk_acuerdos_reuniones_formulario_reuniones1_idx` (`id_reunion` ASC),
  INDEX `fk_acuerdos_reuniones_usuarios1_idx` (`id_usuario_responsable` ASC),
  CONSTRAINT `fk_acuerdos_reuniones_formulario_reuniones1`
    FOREIGN KEY (`id_reunion`)
    REFERENCES `bd_sgc`.`Formulario_Reunion` (`id_reunion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acuerdos_reuniones_usuarios1`
    FOREIGN KEY (`id_usuario_responsable`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Acuerdo_Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Acuerdo_Respuesta` (
  `id_respuesta` INT NOT NULL AUTO_INCREMENT,
  `id_acuerdo` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_respuesta` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_respuesta`),
  INDEX `fk_acuerdos_respuestas_acuerdos_reuniones1_idx` (`id_acuerdo` ASC),
  INDEX `fk_acuerdos_respuestas_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_acuerdos_respuestas_acuerdos_reuniones1`
    FOREIGN KEY (`id_acuerdo`)
    REFERENCES `bd_sgc`.`Acuerdo_Reunion` (`id_acuerdo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acuerdos_respuestas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Recurso` (
  `id_recurso` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_recurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Tecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Tecnica` (
  `id_tecnica` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tecnica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Estatus_Accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Estatus_Accion` (
  `id_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Proviene_De`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Proviene_De` (
  `id_proviene_de` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_proviene_de`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Causa_Raiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Causa_Raiz` (
  `id_causa_raiz` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_causa_raiz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Tipo_Auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Tipo_Auditoria` (
  `id_tipo_auditoria` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_tipo_auditoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Actividad_Accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Actividad_Accion` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `fecha_estimada` DATETIME NOT NULL,
  `fecha_real` DATETIME NOT NULL,
  `porcentaje_avance` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `responsable` INT NOT NULL,
  `accion_proyecto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_actividad`),
  INDEX `fk_actividades_acciones_usuarios1_idx` (`responsable` ASC),
  CONSTRAINT `fk_actividades_acciones_usuarios1`
    FOREIGN KEY (`responsable`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Accion_Correctiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Accion_Correctiva` (
  `id_accion` INT NOT NULL AUTO_INCREMENT,
  `proviene_de` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `numero_auditoria` INT NOT NULL,
  `tipo_auditoria` INT NOT NULL,
  `observacion_norma` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `departamento` INT NOT NULL,
  `responsable_solventar` INT NOT NULL,
  `responsable_verificar` INT NOT NULL,
  `causa_raiz` INT NOT NULL,
  `descripcion_causa_raiz` VARCHAR(200) NOT NULL,
  `accion_correctiva` VARCHAR(200) NOT NULL,
  `fecha_aplicacion` DATETIME NOT NULL,
  `id_estatus_accion` INT NOT NULL,
  `resultado` VARCHAR(100) NOT NULL,
  `numero_accion` INT NOT NULL,
  PRIMARY KEY (`id_accion`),
  INDEX `fk_acciones_correctivas_estatus_acciones1_idx` (`id_estatus_accion` ASC),
  INDEX `fk_acciones_correctivas_usuarios1_idx` (`responsable_solventar` ASC),
  INDEX `fk_acciones_correctivas_usuarios2_idx` (`responsable_verificar` ASC),
  INDEX `fk_acciones_correctivas_proviene_de1_idx` (`proviene_de` ASC),
  INDEX `fk_acciones_correctivas_causa_raiz1_idx` (`causa_raiz` ASC),
  INDEX `fk_acciones_correctivas_departamentos1_idx` (`departamento` ASC),
  INDEX `fk_acciones_correctivas_tipo_auditoria1_idx` (`tipo_auditoria` ASC),
  INDEX `fk_acciones_correctivas_actividades_acciones1_idx` (`numero_accion` ASC),
  CONSTRAINT `fk_acciones_correctivas_estatus_acciones1`
    FOREIGN KEY (`id_estatus_accion`)
    REFERENCES `bd_sgc`.`Estatus_Accion` (`id_estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_usuarios1`
    FOREIGN KEY (`responsable_solventar`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_usuarios2`
    FOREIGN KEY (`responsable_verificar`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_proviene_de1`
    FOREIGN KEY (`proviene_de`)
    REFERENCES `bd_sgc`.`Proviene_De` (`id_proviene_de`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_causa_raiz1`
    FOREIGN KEY (`causa_raiz`)
    REFERENCES `bd_sgc`.`Causa_Raiz` (`id_causa_raiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_departamentos1`
    FOREIGN KEY (`departamento`)
    REFERENCES `bd_sgc`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_tipo_auditoria1`
    FOREIGN KEY (`tipo_auditoria`)
    REFERENCES `bd_sgc`.`Tipo_Auditoria` (`id_tipo_auditoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_correctivas_actividades_acciones1`
    FOREIGN KEY (`numero_accion`)
    REFERENCES `bd_sgc`.`Actividad_Accion` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Tipo_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Tipo_Proyecto` (
  `id_tipo_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Proyecto_Mejora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Proyecto_Mejora` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `numero_proyecto` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `area_aplicacion` INT NOT NULL,
  `proviene_de` INT NOT NULL,
  `tipo_proyecto` INT NOT NULL,
  `situacion_actual` VARCHAR(100) NOT NULL,
  `situacion_deseada` VARCHAR(200) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `area_responsable` INT NOT NULL,
  `responsable` INT NOT NULL,
  `id_tecnica` INT NOT NULL,
  `id_recurso` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`),
  INDEX `fk_proyectos_mejora_departamentos1_idx` (`area_aplicacion` ASC),
  INDEX `fk_proyectos_mejora_departamentos2_idx` (`area_responsable` ASC),
  INDEX `fk_proyectos_mejora_tecnicas1_idx` (`id_tecnica` ASC),
  INDEX `fk_proyectos_mejora_recursos1_idx` (`id_recurso` ASC),
  INDEX `fk_proyectos_mejora_usuarios1_idx` (`responsable` ASC),
  INDEX `fk_proyectos_mejora_proviene_de1_idx` (`proviene_de` ASC),
  INDEX `fk_proyectos_mejora_tipo_proyecto1_idx` (`tipo_proyecto` ASC),
  INDEX `fk_proyectos_mejora_actividades_acciones1_idx` (`numero_proyecto` ASC),
  CONSTRAINT `fk_proyectos_mejora_departamentos1`
    FOREIGN KEY (`area_aplicacion`)
    REFERENCES `bd_sgc`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_departamentos2`
    FOREIGN KEY (`area_responsable`)
    REFERENCES `bd_sgc`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_tecnicas1`
    FOREIGN KEY (`id_tecnica`)
    REFERENCES `bd_sgc`.`Tecnica` (`id_tecnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_recursos1`
    FOREIGN KEY (`id_recurso`)
    REFERENCES `bd_sgc`.`Recurso` (`id_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_usuarios1`
    FOREIGN KEY (`responsable`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_proviene_de1`
    FOREIGN KEY (`proviene_de`)
    REFERENCES `bd_sgc`.`Proviene_De` (`id_proviene_de`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_tipo_proyecto1`
    FOREIGN KEY (`tipo_proyecto`)
    REFERENCES `bd_sgc`.`Tipo_Proyecto` (`id_tipo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_mejora_actividades_acciones1`
    FOREIGN KEY (`numero_proyecto`)
    REFERENCES `bd_sgc`.`Actividad_Accion` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Frecuencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Frecuencia` (
  `id_frecuencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id_frecuencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Indicador` (
  `id_indicador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `objetivo` VARCHAR(200) NOT NULL,
  `meta` VARCHAR(50) NOT NULL,
  `id_frecuencia` INT NOT NULL,
  `tipo_grafica` VARCHAR(50) NOT NULL,
  `informacion_adicional` VARCHAR(100) NOT NULL,
  `id_departamento` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estatus` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_indicador`),
  INDEX `fk_indicadores_frecuencia1_idx` (`id_frecuencia` ASC),
  INDEX `fk_indicadores_departamentos1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_indicadores_frecuencia1`
    FOREIGN KEY (`id_frecuencia`)
    REFERENCES `bd_sgc`.`Frecuencia` (`id_frecuencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicadores_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `bd_sgc`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Resultado_Indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Resultado_Indicador` (
  `id_resultado` INT NOT NULL AUTO_INCREMENT,
  `id_indicador` INT NOT NULL,
  `frecuencia` VARCHAR(50) NOT NULL,
  `valor` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `anio` DATETIME NOT NULL,
  PRIMARY KEY (`id_resultado`),
  INDEX `fk_resultados_indicadores_indicadores1_idx` (`id_indicador` ASC),
  CONSTRAINT `fk_resultados_indicadores_indicadores1`
    FOREIGN KEY (`id_indicador`)
    REFERENCES `bd_sgc`.`Indicador` (`id_indicador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Expresion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Expresion` (
  `id_expresion` INT NOT NULL AUTO_INCREMENT,
  `id_indicador` INT NOT NULL,
  `expresion` VARCHAR(50) NOT NULL,
  `valor_minimo` VARCHAR(50) NOT NULL,
  `valor_maximo` VARCHAR(50) NOT NULL,
  `color_rgb` VARCHAR(50) NOT NULL,
  `simbolo_expresion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_expresion`),
  INDEX `fk_expresiones_indicadores1_idx` (`id_indicador` ASC),
  CONSTRAINT `fk_expresiones_indicadores1`
    FOREIGN KEY (`id_indicador`)
    REFERENCES `bd_sgc`.`Indicador` (`id_indicador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Usuario_Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Usuario_Actividad` (
  `num_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_actividad` INT NOT NULL,
  PRIMARY KEY (`num_empleado`, `id_actividad`),
  INDEX `fk_usuarios_has_actividades_actividades1_idx` (`id_actividad` ASC),
  INDEX `fk_usuarios_has_actividades_usuarios1_idx` (`num_empleado` ASC),
  CONSTRAINT `fk_usuarios_has_actividades_usuarios1`
    FOREIGN KEY (`num_empleado`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_actividades_actividades1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `bd_sgc`.`Actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Usuario_Formulario_Reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Usuario_Formulario_Reunion` (
  `num_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_reunion` INT NOT NULL,
  PRIMARY KEY (`num_empleado`, `id_reunion`),
  INDEX `fk_usuarios_has_formulario_reuniones_formulario_reuniones1_idx` (`id_reunion` ASC),
  INDEX `fk_usuarios_has_formulario_reuniones_usuarios1_idx` (`num_empleado` ASC),
  CONSTRAINT `fk_usuarios_has_formulario_reuniones_usuarios1`
    FOREIGN KEY (`num_empleado`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_formulario_reuniones_formulario_reuniones1`
    FOREIGN KEY (`id_reunion`)
    REFERENCES `bd_sgc`.`Formulario_Reunion` (`id_reunion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Usuario_Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Usuario_Documento` (
  `num_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_documento` INT NOT NULL,
  PRIMARY KEY (`num_empleado`, `id_documento`),
  INDEX `fk_usuarios_has_documentos_documentos1_idx` (`id_documento` ASC),
  INDEX `fk_usuarios_has_documentos_usuarios1_idx` (`num_empleado` ASC),
  CONSTRAINT `fk_usuarios_has_documentos_usuarios1`
    FOREIGN KEY (`num_empleado`)
    REFERENCES `bd_sgc`.`Usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_documentos_documentos1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `bd_sgc`.`Documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sgc`.`Documento_Formulario_Reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sgc`.`Documento_Formulario_Reunion` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `id_reunion` INT NOT NULL,
  PRIMARY KEY (`id_documento`, `id_reunion`),
  INDEX `fk_formulario_reuniones_has_documentos_documentos1_idx` (`id_documento` ASC),
  INDEX `fk_formulario_reuniones_has_documentos_formulario_reuniones_idx` (`id_reunion` ASC),
  CONSTRAINT `fk_formulario_reuniones_has_documentos_formulario_reuniones1`
    FOREIGN KEY (`id_reunion`)
    REFERENCES `bd_sgc`.`Formulario_Reunion` (`id_reunion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_reuniones_has_documentos_documentos1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `bd_sgc`.`Documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
